project:
  type: website

website:
  title: "web"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: visual

